import { type DailyStats, type PageViewSource } from "wasp/entities";
import { HttpError, prisma } from "wasp/server";
import { type GetDailyStats } from "wasp/server/operations";

type DailyStatsWithSources = DailyStats & {
  sources: PageViewSource[];
};

type DailyStatsValues = {
  dailyStats: DailyStatsWithSources;
  weeklyStats: DailyStatsWithSources[];
};

/**
 * Stats vacíos para el primer arranque (o si dailyStatsJob aún no corrió).
 * Mantiene la UI funcional sin nulls que el frontend de Open SaaS no maneja.
 */
const emptyDailyStats = (): DailyStatsWithSources => ({
  id: 0,
  date: new Date(),
  totalViews: 0,
  prevDayViewsChangePercent: "0",
  userCount: 0,
  paidUserCount: 0,
  userDelta: 0,
  paidUserDelta: 0,
  totalRevenue: 0,
  totalProfit: 0,
  sources: [],
});

export const getDailyStats: GetDailyStats<
  void,
  DailyStatsValues
> = async (_args, context) => {
  if (!context.user) {
    throw new HttpError(
      401,
      "Only authenticated users are allowed to perform this operation",
    );
  }

  if (!context.user.isAdmin) {
    throw new HttpError(
      403,
      "Only admins are allowed to perform this operation",
    );
  }

  const statsQuery = {
    orderBy: {
      date: "desc",
    },
    include: {
      sources: true,
    },
  } as const;

  const [dailyStats, weeklyStats] = await prisma.$transaction([
    context.entities.DailyStats.findFirst(statsQuery),
    context.entities.DailyStats.findMany({ ...statsQuery, take: 7 }),
  ]);

  if (!dailyStats) {
    console.log(
      "\x1b[34mNote: No daily stats have been generated by the dailyStatsJob yet. Returning empty stats. \x1b[0m",
    );
    // weeklyStats DEBE tener al menos una entrada porque varios componentes
    // del dashboard (TotalRevenueCard, RevenueAndProfitChart) acceden a
    // weeklyStats[0].* sin optional chaining.
    const empty = emptyDailyStats();
    return { dailyStats: empty, weeklyStats: [empty] };
  }

  return { dailyStats, weeklyStats };
};
